const $=s=>document.querySelector(s);
const scenarios={
 atm:{title:'ATM Withdrawal',desc:'A realistic flow with nested decisions and a retry loop.',code:['START','Read card','PIN correct?','Check balance','Balance sufficient?','Dispense cash','Show error','Retry transaction?','END'],nodes:[['S','START','process'],['C','Read card','process'],['P','PIN correct?','decision'],['B','Check balance','process'],['A','Balance sufficient?','decision'],['W','Dispense cash','process'],['E','Show error','process'],['R','Retry transaction?','loop'],['X','END','process']],edges:[['S','C'],['C','P'],['P','B'],['P','E'],['B','A'],['A','W'],['A','E'],['W','R'],['E','R'],['R','X'],['R','C']],paths:[
  {id:'P1',name:'Successful withdrawal',route:['S','C','P','B','A','W','R','X'],input:'Correct PIN + sufficient balance + no retry',expected:'Cash dispensed and transaction ends.'},
  {id:'P2',name:'Insufficient balance',route:['S','C','P','B','A','E','R','X'],input:'Correct PIN + insufficient balance + no retry',expected:'Decline message shown; no cash dispensed.'},
  {id:'P3',name:'Invalid PIN',route:['S','C','P','E','R','X'],input:'Incorrect PIN + no retry',expected:'Invalid PIN message shown.'},
  {id:'P4',name:'Retry loop',route:['S','C','P','E','R','C','P','B','A','W','R','X'],input:'Incorrect PIN → retry → correct PIN + sufficient balance',expected:'Flow loops back to card/PIN and then completes.'}
]},
 login:{title:'Login + Retry',desc:'A compact login module with lockout and retry behaviour.',code:['START','Enter username + password','Credentials valid?','Open dashboard','Attempts < 3?','Show login error','Lock account','END'],nodes:[['S','START','process'],['L','Enter credentials','process'],['V','Credentials valid?','decision'],['D','Open dashboard','process'],['T','Attempts < 3?','loop'],['E','Show login error','process'],['K','Lock account','process'],['X','END','process']],edges:[['S','L'],['L','V'],['V','D'],['V','E'],['E','T'],['T','L'],['T','K'],['D','X'],['K','X']],paths:[
  {id:'P1',name:'Valid login',route:['S','L','V','D','X'],input:'Correct username + password',expected:'Dashboard opens.'},
  {id:'P2',name:'Invalid then retry',route:['S','L','V','E','T','L','V','D','X'],input:'Wrong credentials once, then correct',expected:'Retry occurs and dashboard opens.'},
  {id:'P3',name:'Invalid and lock',route:['S','L','V','E','T','K','X'],input:'Wrong credentials; maximum attempts reached',expected:'Account is locked.'}
]},
 result:{title:'Student Result',desc:'A marks calculator with pass/fail and distinction branches.',code:['START','Read marks','Marks valid?','Calculate percentage','Percentage ≥ 40?','Percentage ≥ 75?','PASS','FAIL','DISTINCTION','END'],nodes:[['S','START','process'],['M','Read marks','process'],['V','Marks valid?','decision'],['C','Calculate percentage','process'],['P','Percentage ≥ 40?','decision'],['D','Percentage ≥ 75?','decision'],['PASS','PASS','process'],['FAIL','FAIL','process'],['DIST','DISTINCTION','process'],['X','END','process']],edges:[['S','M'],['M','V'],['V','C'],['V','FAIL'],['C','P'],['P','FAIL'],['P','D'],['D','PASS'],['D','DIST'],['PASS','X'],['DIST','X'],['FAIL','X']],paths:[
  {id:'P1',name:'Distinction',route:['S','M','V','C','P','D','DIST','X'],input:'Valid marks; percentage = 82',expected:'Distinction is awarded.'},
  {id:'P2',name:'Normal pass',route:['S','M','V','C','P','D','PASS','X'],input:'Valid marks; percentage = 62',expected:'Student passes.'},
  {id:'P3',name:'Fail',route:['S','M','V','C','P','FAIL','X'],input:'Valid marks; percentage = 32',expected:'Student fails.'},
  {id:'P4',name:'Invalid marks',route:['S','M','V','FAIL','X'],input:'Marks outside 0–100',expected:'Input is rejected.'}
]}
};
let current='atm', selectedPath=0, runTimer;
function complexity(s){return s.edges.length-s.nodes.length+2}
function render(){const s=scenarios[current]; $('#caseTitle').textContent=s.title;$('#caseDesc').textContent=s.desc;$('#code').textContent=s.code.map((x,i)=>String(i+1).padStart(2,'0')+'  '+x).join('\n');$('#gutter').textContent=s.code.map((_,i)=>i+1).join('\n');
 const N=s.nodes.length,E=s.edges.length,V=complexity(s);$('#complexity').textContent=V;$('#nodes').textContent=N;$('#edges').textContent=E;$('#decisions').textContent=V-1;$('#basis').textContent=V;$('#formula').textContent=`${E} − ${N} + 2 = ${V}`;$('#complexityHint').textContent=V<=3?'Low test effort':V<=6?'Moderate test effort':'High test effort';$('#pathCount').textContent=`${s.paths.length} paths`;
 renderGraph(s);renderPaths(s);renderTests(s);$('#runnerStatus').textContent='● READY';$('#runResult').innerHTML='<div class="empty-state"><span>▶</span><b>Select a test and run it</b><small>The execution trace will appear here.</small></div>';}
function renderGraph(s){const svg=$('#graphSvg');svg.innerHTML='';const W=900,H=500;const positions={};const cols=Math.min(4,s.nodes.length);s.nodes.forEach((n,i)=>{let col=i%cols,row=Math.floor(i/cols);positions[n[0]]={x:130+col*215,y:65+row*150};});
 // Improve vertical reading for common small graphs
 if(s.nodes.length<=10){s.nodes.forEach((n,i)=>positions[n[0]]={x:450+(i%2?245:-245),y:55+Math.floor(i/2)*92});positions[s.nodes[0][0]]={x:450,y:35};positions[s.nodes[s.nodes.length-1][0]]={x:450,y:455};}
 const defs=document.createElementNS('http://www.w3.org/2000/svg','defs');defs.innerHTML='<marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="currentColor"/></marker>';svg.appendChild(defs);
 const edgeG=document.createElementNS('http://www.w3.org/2000/svg','g');edgeG.classList.add('edges');s.edges.forEach(([a,b],i)=>{const p1=positions[a],p2=positions[b];let path=document.createElementNS('http://www.w3.org/2000/svg','path');let d;if(a===b||Math.abs(p1.y-p2.y)<20){d=`M ${p1.x} ${p1.y+24} C ${p1.x+80} ${p1.y+85} ${p2.x-80} ${p2.y-85} ${p2.x} ${p2.y-24}`}else d=`M ${p1.x} ${p1.y+24} C ${p1.x} ${p1.y+55} ${p2.x} ${p2.y-55} ${p2.x} ${p2.y-24}`;path.setAttribute('d',d);path.dataset.edge=i;path.setAttribute('marker-end','url(#arrow)');edgeG.appendChild(path)});svg.appendChild(edgeG);
 const nodeG=document.createElementNS('http://www.w3.org/2000/svg','g');s.nodes.forEach(n=>{const p=positions[n[0]],g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('g-node',n[2]);g.dataset.id=n[0];const r=document.createElementNS('http://www.w3.org/2000/svg','rect');r.setAttribute('x',p.x-75);r.setAttribute('y',p.y-24);r.setAttribute('width',150);r.setAttribute('height',48);r.setAttribute('rx',14);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',p.x);t.setAttribute('y',p.y+5);t.textContent=n[1];g.append(r,t);g.onclick=()=>{const idx=s.nodes.findIndex(x=>x[0]===n[0]);toast(`Node ${idx+1}: ${n[1]}`)};nodeG.appendChild(g)});svg.appendChild(nodeG);}
function renderPaths(s){$('#pathsList').innerHTML=s.paths.map((p,i)=>`<button class="path-row ${i===selectedPath?'selected':''}" data-i="${i}"><span class="path-num">${p.id}</span><span class="path-main"><b>${p.name}</b><small>${p.route.join(' → ')}</small></span><span class="path-arrow">›</span></button>`).join('');document.querySelectorAll('.path-row').forEach(b=>b.onclick=()=>{selectedPath=+b.dataset.i;renderPaths(s);highlightPath(s,s.paths[selectedPath]);$('#testSelect').value=selectedPath});}
function renderTests(s){$('#testSelect').innerHTML=s.paths.map((p,i)=>`<option value="${i}">${p.id} · ${p.name}</option>`).join('');$('#testSelect').value=selectedPath}
function highlightPath(s,p){document.querySelectorAll('.g-node').forEach(n=>n.classList.remove('path-active'));document.querySelectorAll('#graphSvg .edges path').forEach(e=>e.classList.remove('path-active'));p.route.forEach(id=>document.querySelector(`.g-node[data-id="${CSS.escape(id)}"]`)?.classList.add('path-active'));for(let i=0;i<p.route.length-1;i++){const a=p.route[i],b=p.route[i+1];const edgeIndex=s.edges.findIndex(e=>e[0]===a&&e[1]===b);if(edgeIndex>=0)document.querySelector(`#graphSvg .edges path[data-edge="${edgeIndex}"]`)?.classList.add('path-active')}}
function runTest(){const s=scenarios[current],p=s.paths[+$('#testSelect').value];selectedPath=+$('#testSelect').value;renderPaths(s);highlightPath(s,p);clearInterval(runTimer);$('#runnerStatus').textContent='● RUNNING';let step=0;const result=$('#runResult');result.innerHTML=`<div class="run-head"><div><b>${p.id} · ${p.name}</b><small>${p.input}</small></div><span class="running">EXECUTING</span></div><div class="progress"><i id="progressBar"></i></div><div id="trace" class="trace"></div>`;const trace=$('#trace');const tick=()=>{if(step>=p.route.length){clearInterval(runTimer);$('#runnerStatus').textContent='● PASSED';const done=document.createElement('div');done.className='pass-box';done.innerHTML=`<b>✓ Test passed</b><span>${p.expected}</span></div>`;trace.appendChild(done);toast(`${p.id} completed`);return}const id=p.route[step],node=s.nodes.find(n=>n[0]===id);const line=document.createElement('div');line.className='trace-line';line.innerHTML=`<span>${String(step+1).padStart(2,'0')}</span><b>${node[1]}</b><em>${node[2]==='decision'?'DECISION':node[2]==='loop'?'LOOP':'STEP'}</em>`;trace.appendChild(line);$('#progressBar').style.width=((step+1)/p.route.length*100)+'%';step++};tick();runTimer=setInterval(tick,420)}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
$('#scenario').onchange=()=>{current=$('#scenario').value;selectedPath=0;render()};$('#analyze').onclick=()=>{render();toast('Analysis recalculated')};$('#testSelect').onchange=()=>{selectedPath=+$('#testSelect').value;highlightPath(scenarios[current],scenarios[current].paths[selectedPath]);renderPaths(scenarios[current])};$('#runTest').onclick=runTest;$('#reset').onclick=()=>{current='atm';$('#scenario').value='atm';selectedPath=0;render();toast('Workspace reset')};
$('#export').onclick=()=>{const s=scenarios[current],V=complexity(s);const report=`BASISPATH ANALYSIS REPORT\n==========================\nCase: ${s.title}\n\nNodes: ${s.nodes.length}\nEdges: ${s.edges.length}\nDecision points: ${V-1}\nCyclomatic complexity: ${V}\nFormula: E - N + 2 = ${s.edges.length} - ${s.nodes.length} + 2 = ${V}\nMinimum basis paths: ${s.paths.length}\n\nINDEPENDENT PATHS\n${s.paths.map(p=>`${p.id}: ${p.name}\nRoute: ${p.route.join(' -> ')}\nInput: ${p.input}\nExpected: ${p.expected}`).join('\n\n')}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([report],{type:'text/plain'}));a.download='basispath-report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Report exported')};
function syncThemeLabel(){const dark=document.body.classList.contains('dark');const label=$('#themeLabel');if(label)label.textContent=dark?'Light mode':'Dark mode';$('#theme')?.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode')}
$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('bp-dark',document.body.classList.contains('dark'));syncThemeLabel()};if(localStorage.getItem('bp-dark')==='true')document.body.classList.add('dark');syncThemeLabel();
$('#showFormula').onclick=()=>$('#modal').classList.add('show');$('#closeModal').onclick=$('#closeModal2').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')};
render();

// ===== Navigation scroll spy =====
(function setupSectionNavigation(){
  const links=[...document.querySelectorAll('.sidebar nav a[href^="#"]')];
  const sections=links.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);
  if(!links.length || !sections.length) return;
  const setActive=(id)=>{
    links.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${id}`));
  };
  const observer=new IntersectionObserver(entries=>{
    const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];
    if(visible) setActive(visible.target.id);
  },{rootMargin:'-95px 0px -55% 0px',threshold:[0,.15,.35,.6]});
  sections.forEach(section=>observer.observe(section));
  links.forEach(link=>link.addEventListener('click',()=>setActive(link.getAttribute('href').slice(1))));
})();
